### ISSUE TITLE
Bug: the standard logviewer starts at the top with the oldest logs instead of at the bottem where the newest logs are

### ISSUE THREAD

**Issue by Joren-Thijs-KasparSolutions** [wim07101993/fox_logging#1]
the standard logviewer starts at the top with the oldest logs instead of at the bottem where the newest logs are

**Comment by wim07101993** [comment]
The flutter_fox_logging package has been moved to it's [own repo](https://github.com/wim07101993/flutter_fox_logging/) but this issue should be solved with [this pull-request](https://github.com/wim07101993/flutter_fox_logging/pull/15)
